FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build-env

ENV ASPNETCORE_URLS="https://*:8080;http://*:8000"
ENV ASPNETCORE_ENVIRONMENT="Development"
ENV DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1
# Use native linux file polling for better performance
WORKDIR /app
COPY ./ ./
ENV PATH $PATH:/root/.dotnet/tools
RUN dotnet tool install --global dotnet-ef
EXPOSE 8080
ENTRYPOINT dotnet watch run --project src/Gateway